package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0

/**
 * AcompananteReservaDTO generated by hbm2java
 */
public class AcompananteReservaDTO implements java.io.Serializable {

	private int idPersona;
	private int idDetalleReserva;
	private int flagEntregaTarjeta;
	private int estado;
	
	public AcompananteReservaDTO() {
		super();
	}
	public AcompananteReservaDTO(int idPersona, int idDetalleReserva,
			int flagEntregaTarjeta, int estado) {
		super();
		this.idPersona = idPersona;
		this.idDetalleReserva = idDetalleReserva;
		this.flagEntregaTarjeta = flagEntregaTarjeta;
		this.estado = estado;
	}
	public int getIdPersona() {
		return idPersona;
	}
	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}
	public int getIdDetalleReserva() {
		return idDetalleReserva;
	}
	public void setIdDetalleReserva(int idDetalleReserva) {
		this.idDetalleReserva = idDetalleReserva;
	}
	public int getFlagEntregaTarjeta() {
		return flagEntregaTarjeta;
	}
	public void setFlagEntregaTarjeta(int flagEntregaTarjeta) {
		this.flagEntregaTarjeta = flagEntregaTarjeta;
	}
	public int getEstado() {
		return estado;
	}
	public void setEstado(int estado) {
		this.estado = estado;
	}
	
	

}
