package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * AmbienteDTO generated by hbm2java
 */
public class AmbienteDTO implements java.io.Serializable {

	private int idAmbiente;
	private String descripcion;
	private double precio;
	private String numberoLocal;
	private String urlimagen;
	private int piso;
	private int estado;
	private int cantCuartos;
	private int capacidadPersonas;
	private int cantAsientosConPrivilegios;
	private int flagMiniBar;
	private int flagAmbienteOferta;
	private int cantMinReservasParaPromocion;
	private AmbienteDTO ambienteDTO;
	private int codAmbiente;
	
	public AmbienteDTO() {
	}

	public AmbienteDTO(int idAmbiente, String descripcion, double precio,
			String numberoLocal, String urlimagen, int piso, int estado,
			int cantCuartos, int capacidadPersonas,
			int cantAsientosConPrivilegios, int flagMiniBar,
			int flagAmbienteOferta, int cantMinReservasParaPromocion,
			AmbienteDTO ambienteDTO, int codAmbiente) {
		super();
		this.idAmbiente = idAmbiente;
		this.descripcion = descripcion;
		this.precio = precio;
		this.numberoLocal = numberoLocal;
		this.urlimagen = urlimagen;
		this.piso = piso;
		this.estado = estado;
		this.cantCuartos = cantCuartos;
		this.capacidadPersonas = capacidadPersonas;
		this.cantAsientosConPrivilegios = cantAsientosConPrivilegios;
		this.flagMiniBar = flagMiniBar;
		this.flagAmbienteOferta = flagAmbienteOferta;
		this.cantMinReservasParaPromocion = cantMinReservasParaPromocion;
		this.ambienteDTO = ambienteDTO;
		this.codAmbiente = codAmbiente;
	}

	public int getIdAmbiente() {
		return idAmbiente;
	}

	public void setIdAmbiente(int idAmbiente) {
		this.idAmbiente = idAmbiente;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getPrecio() {
		return precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public String getNumberoLocal() {
		return numberoLocal;
	}

	public void setNumberoLocal(String numberoLocal) {
		this.numberoLocal = numberoLocal;
	}

	public String getUrlimagen() {
		return urlimagen;
	}

	public void setUrlimagen(String urlimagen) {
		this.urlimagen = urlimagen;
	}

	public int getPiso() {
		return piso;
	}

	public void setPiso(int piso) {
		this.piso = piso;
	}

	public int getEstado() {
		return estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public int getCantCuartos() {
		return cantCuartos;
	}

	public void setCantCuartos(int cantCuartos) {
		this.cantCuartos = cantCuartos;
	}

	public int getCapacidadPersonas() {
		return capacidadPersonas;
	}

	public void setCapacidadPersonas(int capacidadPersonas) {
		this.capacidadPersonas = capacidadPersonas;
	}

	public int getCantAsientosConPrivilegios() {
		return cantAsientosConPrivilegios;
	}

	public void setCantAsientosConPrivilegios(int cantAsientosConPrivilegios) {
		this.cantAsientosConPrivilegios = cantAsientosConPrivilegios;
	}

	public int getFlagMiniBar() {
		return flagMiniBar;
	}

	public void setFlagMiniBar(int flagMiniBar) {
		this.flagMiniBar = flagMiniBar;
	}

	public int getFlagAmbienteOferta() {
		return flagAmbienteOferta;
	}

	public void setFlagAmbienteOferta(int flagAmbienteOferta) {
		this.flagAmbienteOferta = flagAmbienteOferta;
	}

	public int getCantMinReservasParaPromocion() {
		return cantMinReservasParaPromocion;
	}

	public void setCantMinReservasParaPromocion(int cantMinReservasParaPromocion) {
		this.cantMinReservasParaPromocion = cantMinReservasParaPromocion;
	}

	public AmbienteDTO getAmbienteDTO() {
		return ambienteDTO;
	}

	public void setAmbienteDTO(AmbienteDTO ambienteDTO) {
		this.ambienteDTO = ambienteDTO;
	}

	public int getCodAmbiente() {
		return codAmbiente;
	}

	public void setCodAmbiente(int codAmbiente) {
		this.codAmbiente = codAmbiente;
	}

	@Override
	public String toString() {
		return "AmbienteDTO [idAmbiente=" + idAmbiente + ", descripcion="
				+ descripcion + ", precio=" + precio + ", numberoLocal="
				+ numberoLocal + ", urlimagen=" + urlimagen + ", piso=" + piso
				+ ", estado=" + estado + ", cantCuartos=" + cantCuartos
				+ ", capacidadPersonas=" + capacidadPersonas
				+ ", cantAsientosConPrivilegios=" + cantAsientosConPrivilegios
				+ ", flagMiniBar=" + flagMiniBar + ", flagAmbienteOferta="
				+ flagAmbienteOferta + ", cantMinReservasParaPromocion="
				+ cantMinReservasParaPromocion + ", ambienteDTO=" + ambienteDTO
				+ ", codAmbiente=" + codAmbiente + "]";
	}

	
	
	
	
}
