package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0

/**
 * ConsumoDTO generated by hbm2java
 */
public class ConsumoDTO implements java.io.Serializable {

	private int idConsumo;
	private ProductoGlobalDTO productoGlobalDTO;
	private PersonaTarjetaDTO personaTarjetaDTO;
	private double precioGrabado;
	private int cantidad;
	private double descuento;
	private String fechaDeConsumo;
	private int estado;
	
	public ConsumoDTO(int idConsumo, ProductoGlobalDTO productoGlobalDTO,
			PersonaTarjetaDTO personaTarjetaDTO, double precioGrabado,
			int cantidad, double descuento, String fechaDeConsumo, int estado) {
		super();
		this.idConsumo = idConsumo;
		this.productoGlobalDTO = productoGlobalDTO;
		this.personaTarjetaDTO = personaTarjetaDTO;
		this.precioGrabado = precioGrabado;
		this.cantidad = cantidad;
		this.descuento = descuento;
		this.fechaDeConsumo = fechaDeConsumo;
		this.estado = estado;
	}
	public ConsumoDTO() {
		super();
		// TODO Auto-generated constructor stub
	}
	public int getIdConsumo() {
		return idConsumo;
	}
	public void setIdConsumo(int idConsumo) {
		this.idConsumo = idConsumo;
	}
	public ProductoGlobalDTO getProductoGlobalDTO() {
		return productoGlobalDTO;
	}
	public void setProductoGlobalDTO(ProductoGlobalDTO productoGlobalDTO) {
		this.productoGlobalDTO = productoGlobalDTO;
	}
	public PersonaTarjetaDTO getPersonaTarjetaDTO() {
		return personaTarjetaDTO;
	}
	public void setPersonaTarjetaDTO(PersonaTarjetaDTO personaTarjetaDTO) {
		this.personaTarjetaDTO = personaTarjetaDTO;
	}
	public double getPrecioGrabado() {
		return precioGrabado;
	}
	public void setPrecioGrabado(double precioGrabado) {
		this.precioGrabado = precioGrabado;
	}
	public int getCantidad() {
		return cantidad;
	}
	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
	public double getDescuento() {
		return descuento;
	}
	public void setDescuento(double descuento) {
		this.descuento = descuento;
	}
	public String getFechaDeConsumo() {
		return fechaDeConsumo;
	}
	public void setFechaDeConsumo(String fechaDeConsumo) {
		this.fechaDeConsumo = fechaDeConsumo;
	}
	public int getEstado() {
		return estado;
	}
	public void setEstado(int estado) {
		this.estado = estado;
	}
	@Override
	public String toString() {
		return "ConsumoDTO [idConsumo=" + idConsumo + ", productoGlobalDTO="
				+ productoGlobalDTO + ", personaTarjetaDTO="
				+ personaTarjetaDTO + ", precioGrabado=" + precioGrabado
				+ ", cantidad=" + cantidad + ", descuento=" + descuento
				+ ", fechaDeConsumo=" + fechaDeConsumo + ", estado=" + estado
				+ "]";
	}
	
	

}
