package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0

/**
 * DefaultProdHabitacionDTO generated by hbm2java
 */
public class DefaultProdHabitacionDTO implements java.io.Serializable {

	private int idAmbiente;
	private int idProductoServicio;
	private int cantidad;
	private double precioGrabado;

	public DefaultProdHabitacionDTO() {
	}

	public DefaultProdHabitacionDTO(int idAmbiente, int idProductoServicio,
			int cantidad, double precioGrabado) {
		super();
		this.idAmbiente = idAmbiente;
		this.idProductoServicio = idProductoServicio;
		this.cantidad = cantidad;
		this.precioGrabado = precioGrabado;
	}

	public int getIdAmbiente() {
		return idAmbiente;
	}

	public void setIdAmbiente(int idAmbiente) {
		this.idAmbiente = idAmbiente;
	}

	public int getIdProductoServicio() {
		return idProductoServicio;
	}

	public void setIdProductoServicio(int idProductoServicio) {
		this.idProductoServicio = idProductoServicio;
	}

	public int getCantidad() {
		return cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public double getPrecioGrabado() {
		return precioGrabado;
	}

	public void setPrecioGrabado(double precioGrabado) {
		this.precioGrabado = precioGrabado;
	}

	@Override
	public String toString() {
		return "DefaultProdHabitacionDTO [idAmbiente=" + idAmbiente
				+ ", idProductoServicio=" + idProductoServicio + ", cantidad="
				+ cantidad + ", precioGrabado=" + precioGrabado + "]";
	}

	
}
