package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * DetalleReservaDTO generated by hbm2java
 */
public class DetalleReservaDTO implements java.io.Serializable {

	private int idDetalleReserva;
	private AmbienteDTO ambienteDTO;
	private ReservaDTO reservaDTO;
	private String fecInicio;
	private String fecFin;
	private int estadoActivacionReserva;

	public DetalleReservaDTO() {
	}

	public DetalleReservaDTO(int idDetalleReserva, AmbienteDTO ambienteDTO,
			ReservaDTO reservaDTO, String fecInicio, String fecFin,
			int estadoActivacionReserva) {
		super();
		this.idDetalleReserva = idDetalleReserva;
		this.ambienteDTO = ambienteDTO;
		this.reservaDTO = reservaDTO;
		this.fecInicio = fecInicio;
		this.fecFin = fecFin;
		this.estadoActivacionReserva = estadoActivacionReserva;
	}

	public int getIdDetalleReserva() {
		return idDetalleReserva;
	}

	public void setIdDetalleReserva(int idDetalleReserva) {
		this.idDetalleReserva = idDetalleReserva;
	}

	public AmbienteDTO getAmbienteDTO() {
		return ambienteDTO;
	}

	public void setAmbienteDTO(AmbienteDTO ambienteDTO) {
		this.ambienteDTO = ambienteDTO;
	}

	public ReservaDTO getReservaDTO() {
		return reservaDTO;
	}

	public void setReservaDTO(ReservaDTO reservaDTO) {
		this.reservaDTO = reservaDTO;
	}

	public String getFecInicio() {
		return fecInicio;
	}

	public void setFecInicio(String fecInicio) {
		this.fecInicio = fecInicio;
	}

	public String getFecFin() {
		return fecFin;
	}

	public void setFecFin(String fecFin) {
		this.fecFin = fecFin;
	}

	public int getEstadoActivacionReserva() {
		return estadoActivacionReserva;
	}

	public void setEstadoActivacionReserva(int estadoActivacionReserva) {
		this.estadoActivacionReserva = estadoActivacionReserva;
	}

	@Override
	public String toString() {
		return "DetalleReservaDTO [idDetalleReserva=" + idDetalleReserva
				+ ", ambienteDTO=" + ambienteDTO + ", reservaDTO=" + reservaDTO
				+ ", fecInicio=" + fecInicio + ", fecFin=" + fecFin
				+ ", estadoActivacionReserva=" + estadoActivacionReserva + "]";
	}

	
	
}
