package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * EmpleadoDTO generated by hbm2java
 */
public class EmpleadoDTO implements java.io.Serializable {

	private int idEmpleado;
	private PersonaDTO personaDTO;
	private int disponibilidad;

	public EmpleadoDTO() {
	}

	public EmpleadoDTO(int idEmpleado, PersonaDTO personaDTO, int disponibilidad) {
		super();
		this.idEmpleado = idEmpleado;
		this.personaDTO = personaDTO;
		this.disponibilidad = disponibilidad;
	}

	public int getIdEmpleado() {
		return idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public PersonaDTO getPersonaDTO() {
		return personaDTO;
	}

	public void setPersonaDTO(PersonaDTO personaDTO) {
		this.personaDTO = personaDTO;
	}

	public int getDisponibilidad() {
		return disponibilidad;
	}

	public void setDisponibilidad(int disponibilidad) {
		this.disponibilidad = disponibilidad;
	}

	@Override
	public String toString() {
		return "EmpleadoDTO [idEmpleado=" + idEmpleado + ", personaDTO="
				+ personaDTO + ", disponibilidad=" + disponibilidad + "]";
	}

	
}
