package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0

/**
 * IncidenciaAmbienteDTO generated by hbm2java
 */
public class IncidenciaAmbienteDTO implements java.io.Serializable {

	private int idIncidenciasAmbiente;
	private EmpleadoDTO empleadoDTO;
	private DetalleReservaDTO detalleReservaDTO;
	private String descripcionInsidente;
	private String fechaRevision;

	public IncidenciaAmbienteDTO() {
	}

	public IncidenciaAmbienteDTO(EmpleadoDTO empleadoDTO,
			DetalleReservaDTO detalleReservaDTO) {
		this.empleadoDTO = empleadoDTO;
		this.detalleReservaDTO = detalleReservaDTO;
	}

	public IncidenciaAmbienteDTO(EmpleadoDTO empleadoDTO,
			DetalleReservaDTO detalleReservaDTO, String descripcionInsidente,
			String fechaRevision) {
		this.empleadoDTO = empleadoDTO;
		this.detalleReservaDTO = detalleReservaDTO;
		this.descripcionInsidente = descripcionInsidente;
		this.fechaRevision = fechaRevision;
	}

	public int getIdIncidenciasAmbiente() {
		return this.idIncidenciasAmbiente;
	}

	public void setIdIncidenciasAmbiente(int idIncidenciasAmbiente) {
		this.idIncidenciasAmbiente = idIncidenciasAmbiente;
	}

	public EmpleadoDTO getEmpleadoDTO() {
		return this.empleadoDTO;
	}

	public void setEmpleadoDTO(EmpleadoDTO empleadoDTO) {
		this.empleadoDTO = empleadoDTO;
	}

	public DetalleReservaDTO getDetalleReservaDTO() {
		return this.detalleReservaDTO;
	}

	public void setDetalleReservaDTO(DetalleReservaDTO detalleReservaDTO) {
		this.detalleReservaDTO = detalleReservaDTO;
	}

	public String getDescripcionInsidente() {
		return this.descripcionInsidente;
	}

	public void setDescripcionInsidente(String descripcionInsidente) {
		this.descripcionInsidente = descripcionInsidente;
	}

	public String getFechaRevision() {
		return this.fechaRevision;
	}

	public void setFechaRevision(String fechaRevision) {
		this.fechaRevision = fechaRevision;
	}

}
