package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0

/**
 * PerfilMenuDTO generated by hbm2java
 */
public class PerfilMenuDTO implements java.io.Serializable {

	private int idPerfil;
	private int idMenu;
	
	public PerfilMenuDTO() {
	}

	public PerfilMenuDTO(int idPerfil, int idMenu) {
		super();
		this.idPerfil = idPerfil;
		this.idMenu = idMenu;
	}

	public int getIdPerfil() {
		return idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public int getIdMenu() {
		return idMenu;
	}

	public void setIdMenu(int idMenu) {
		this.idMenu = idMenu;
	}

	@Override
	public String toString() {
		return "PerfilMenuDTO [idPerfil=" + idPerfil + ", idMenu=" + idMenu
				+ "]";
	}

	

}
