package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * PerfilDTO generated by hbm2java
 */
public class PerfilDTO implements java.io.Serializable {

	private int idPerfil;
	private String descripcion;

	public PerfilDTO() {
	}

	public PerfilDTO(int idPerfil, String descripcion) {
		super();
		this.idPerfil = idPerfil;
		this.descripcion = descripcion;
	}

	public int getIdPerfil() {
		return idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "PerfilDTO [idPerfil=" + idPerfil + ", descripcion="
				+ descripcion + "]";
	}

	
	
	
}
