package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * PersonaTarjetaDTO generated by hbm2java
 */
public class PersonaTarjetaDTO implements java.io.Serializable {

	private int idTarjetaPersona;
	private PersonaTarjetaDTO personaTarjetaDTO;
	private PersonaDTO personaDTO;
	private TarjetaDTO tarjetaDTO;
	private ReservaDTO reservaDTO;

	public PersonaTarjetaDTO() {
	}

	public PersonaTarjetaDTO(int idTarjetaPersona,
			PersonaTarjetaDTO personaTarjetaDTO, PersonaDTO personaDTO,
			TarjetaDTO tarjetaDTO, ReservaDTO reservaDTO) {
		super();
		this.idTarjetaPersona = idTarjetaPersona;
		this.personaTarjetaDTO = personaTarjetaDTO;
		this.personaDTO = personaDTO;
		this.tarjetaDTO = tarjetaDTO;
		this.reservaDTO = reservaDTO;
	}

	public int getIdTarjetaPersona() {
		return idTarjetaPersona;
	}

	public void setIdTarjetaPersona(int idTarjetaPersona) {
		this.idTarjetaPersona = idTarjetaPersona;
	}

	public PersonaTarjetaDTO getPersonaTarjetaDTO() {
		return personaTarjetaDTO;
	}

	public void setPersonaTarjetaDTO(PersonaTarjetaDTO personaTarjetaDTO) {
		this.personaTarjetaDTO = personaTarjetaDTO;
	}

	public PersonaDTO getPersonaDTO() {
		return personaDTO;
	}

	public void setPersonaDTO(PersonaDTO personaDTO) {
		this.personaDTO = personaDTO;
	}

	public TarjetaDTO getTarjetaDTO() {
		return tarjetaDTO;
	}

	public void setTarjetaDTO(TarjetaDTO tarjetaDTO) {
		this.tarjetaDTO = tarjetaDTO;
	}

	public ReservaDTO getReservaDTO() {
		return reservaDTO;
	}

	public void setReservaDTO(ReservaDTO reservaDTO) {
		this.reservaDTO = reservaDTO;
	}

	@Override
	public String toString() {
		return "PersonaTarjetaDTO [idTarjetaPersona=" + idTarjetaPersona
				+ ", personaTarjetaDTO=" + personaTarjetaDTO + ", personaDTO="
				+ personaDTO + ", tarjetaDTO=" + tarjetaDTO + ", reservaDTO="
				+ reservaDTO + "]";
	}

	
	
	
}
