package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * PersonaDTO generated by hbm2java
 */
public class PersonaDTO {

	private int idPersona;
	private TipoDocumentoDTO tipoDocumentoDTO;
	private String nombres;
	private String apePaterno;
	private String apeMaterno;
	private String numDocumento;
	private int telf;
	private int cel;
	private String email;
	private int estado;
	
	public PersonaDTO(int idPersona, TipoDocumentoDTO tipoDocumentoDTO,
			String nombres, String apePaterno, String apeMaterno,
			String numDocumento, int telf, int cel, String email, int estado) {
		super();
		this.idPersona = idPersona;
		this.tipoDocumentoDTO = tipoDocumentoDTO;
		this.nombres = nombres;
		this.apePaterno = apePaterno;
		this.apeMaterno = apeMaterno;
		this.numDocumento = numDocumento;
		this.telf = telf;
		this.cel = cel;
		this.email = email;
		this.estado = estado;
	}
	public PersonaDTO() {
		super();
		// TODO Auto-generated constructor stub
	}
	public int getIdPersona() {
		return idPersona;
	}
	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}
	public TipoDocumentoDTO getTipoDocumentoDTO() {
		return tipoDocumentoDTO;
	}
	public void setTipoDocumentoDTO(TipoDocumentoDTO tipoDocumentoDTO) {
		this.tipoDocumentoDTO = tipoDocumentoDTO;
	}
	public String getNombres() {
		return nombres;
	}
	public void setNombres(String nombres) {
		this.nombres = nombres;
	}
	public String getApePaterno() {
		return apePaterno;
	}
	public void setApePaterno(String apePaterno) {
		this.apePaterno = apePaterno;
	}
	public String getApeMaterno() {
		return apeMaterno;
	}
	public void setApeMaterno(String apeMaterno) {
		this.apeMaterno = apeMaterno;
	}
	public String getNumDocumento() {
		return numDocumento;
	}
	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}
	public int getTelf() {
		return telf;
	}
	public void setTelf(int telf) {
		this.telf = telf;
	}
	public int getCel() {
		return cel;
	}
	public void setCel(int cel) {
		this.cel = cel;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public int getEstado() {
		return estado;
	}
	public void setEstado(int estado) {
		this.estado = estado;
	}
	@Override
	public String toString() {
		return "PersonaDTO [idPersona=" + idPersona + ", tipoDocumentoDTO="
				+ tipoDocumentoDTO + ", nombres=" + nombres + ", apePaterno="
				+ apePaterno + ", apeMaterno=" + apeMaterno + ", numDocumento="
				+ numDocumento + ", telf=" + telf + ", cel=" + cel + ", email="
				+ email + ", estado=" + estado + "]";
	}
		
}
