package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * ProductoServicioDTO generated by hbm2java
 */
public class ProductoServicioDTO implements java.io.Serializable {

	private int idProducto;
	private double precio;
	private String descripcion;

	public ProductoServicioDTO() {
	}

	public ProductoServicioDTO(int idProducto, double precio, String descripcion) {
		super();
		this.idProducto = idProducto;
		this.precio = precio;
		this.descripcion = descripcion;
	}

	public int getIdProducto() {
		return idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public double getPrecio() {
		return precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "ProductoServicioDTO [idProducto=" + idProducto + ", precio="
				+ precio + ", descripcion=" + descripcion + "]";
	}
	
	
}
