package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * ProductoGlobalDTO generated by hbm2java
 */
public class ProductoGlobalDTO implements java.io.Serializable {

	private int idProductoGlobal;
	private TipoProductoDTO tipoProductoDTO;
	private int idProducto;
	private String descripcion;
	
	public ProductoGlobalDTO() {
	}

	public ProductoGlobalDTO(int idProductoGlobal,
			TipoProductoDTO tipoProductoDTO, int idProducto, String descripcion) {
		super();
		this.idProductoGlobal = idProductoGlobal;
		this.tipoProductoDTO = tipoProductoDTO;
		this.idProducto = idProducto;
		this.descripcion = descripcion;
	}

	public int getIdProductoGlobal() {
		return idProductoGlobal;
	}

	public void setIdProductoGlobal(int idProductoGlobal) {
		this.idProductoGlobal = idProductoGlobal;
	}

	public TipoProductoDTO getTipoProductoDTO() {
		return tipoProductoDTO;
	}

	public void setTipoProductoDTO(TipoProductoDTO tipoProductoDTO) {
		this.tipoProductoDTO = tipoProductoDTO;
	}

	public int getIdProducto() {
		return idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
}
