package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0

/**
 * RecepcionistaReservaDTO generated by hbm2java
 */
public class RecepcionistaReservaDTO implements java.io.Serializable {

	private int idEmpleado;
	private int idDetalleReserva;
	private int recepcionistaOperacion;

	public RecepcionistaReservaDTO() {
	}

	public RecepcionistaReservaDTO(int idEmpleado, int idDetalleReserva,
			int recepcionistaOperacion) {
		super();
		this.idEmpleado = idEmpleado;
		this.idDetalleReserva = idDetalleReserva;
		this.recepcionistaOperacion = recepcionistaOperacion;
	}

	public int getIdEmpleado() {
		return idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public int getIdDetalleReserva() {
		return idDetalleReserva;
	}

	public void setIdDetalleReserva(int idDetalleReserva) {
		this.idDetalleReserva = idDetalleReserva;
	}

	public int getRecepcionistaOperacion() {
		return recepcionistaOperacion;
	}

	public void setRecepcionistaOperacion(int recepcionistaOperacion) {
		this.recepcionistaOperacion = recepcionistaOperacion;
	}

	
	
}
