package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * ReservaDTO generated by hbm2java
 */
public class ReservaDTO implements java.io.Serializable {

	private int idReserva;
	private ClienteDTO clienteDTO;
	private String fechaRegistro;
	private int estado;

	public ReservaDTO() {
	}

	public ReservaDTO(int idReserva, ClienteDTO clienteDTO,
			String fechaRegistro, int estado) {
		super();
		this.idReserva = idReserva;
		this.clienteDTO = clienteDTO;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
	}

	public int getIdReserva() {
		return idReserva;
	}

	public void setIdReserva(int idReserva) {
		this.idReserva = idReserva;
	}

	public ClienteDTO getClienteDTO() {
		return clienteDTO;
	}

	public void setClienteDTO(ClienteDTO clienteDTO) {
		this.clienteDTO = clienteDTO;
	}

	public String getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public int getEstado() {
		return estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Override
	public String toString() {
		return "ReservaDTO [idReserva=" + idReserva + ", clienteDTO="
				+ clienteDTO + ", fechaRegistro=" + fechaRegistro + ", estado="
				+ estado + "]";
	}
	
}
