package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * TarjetaDTO generated by hbm2java
 */
public class TarjetaDTO implements java.io.Serializable {

	private int idTarjeta;
	private long numero;
	private int estado;

	public TarjetaDTO() {
	}

	public TarjetaDTO(int idTarjeta, long numero, int estado) {
		super();
		this.idTarjeta = idTarjeta;
		this.numero = numero;
		this.estado = estado;
	}

	public int getIdTarjeta() {
		return idTarjeta;
	}

	public void setIdTarjeta(int idTarjeta) {
		this.idTarjeta = idTarjeta;
	}

	public long getNumero() {
		return numero;
	}

	public void setNumero(long numero) {
		this.numero = numero;
	}

	public int getEstado() {
		return estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Override
	public String toString() {
		return "TarjetaDTO [idTarjeta=" + idTarjeta + ", numero=" + numero
				+ ", estado=" + estado + "]";
	}

	
	
}
