package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * TipoDocumentoDTO generated by hbm2java
 */
public class TipoDocumentoDTO implements java.io.Serializable {

	private int idTipoDocumento;
	private String descripcion;
	
	public TipoDocumentoDTO() {
	}

	public TipoDocumentoDTO(int idTipoDocumento, String descripcion) {
		super();
		this.idTipoDocumento = idTipoDocumento;
		this.descripcion = descripcion;
	}

	public int getIdTipoDocumento() {
		return idTipoDocumento;
	}

	public void setIdTipoDocumento(int idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "TipoDocumentoDTO [idTipoDocumento=" + idTipoDocumento
				+ ", descripcion=" + descripcion + "]";
	}

	
	
	
}
