package pe.libertadores.dto;

// Generated 04-ene-2014 20:15:56 by Hibernate Tools 4.0.0


/**
 * TipoProductoDTO generated by hbm2java
 */
public class TipoProductoDTO implements java.io.Serializable {

	private int idTipoProducto;
	private String descripcion;

	public TipoProductoDTO() {
	}

	public TipoProductoDTO(int idTipoProducto, String descripcion) {
		super();
		this.idTipoProducto = idTipoProducto;
		this.descripcion = descripcion;
	}

	public int getIdTipoProducto() {
		return idTipoProducto;
	}

	public void setIdTipoProducto(int idTipoProducto) {
		this.idTipoProducto = idTipoProducto;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "TipoProductoDTO [idTipoProducto=" + idTipoProducto
				+ ", descripcion=" + descripcion + "]";
	}

	
	
}
